/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
  export interface RouteNamedMap {
    '//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/': RouteRecordInfo<'//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/', '/Users/incruisesja/Documents/GitHub/personal-website/client/src/pages', Record<never, never>, Record<never, never>>,
    '//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/blog/': RouteRecordInfo<'//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/blog/', '/Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/blog', Record<never, never>, Record<never, never>>,
    '//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/blog/[slug]': RouteRecordInfo<'//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/blog/[slug]', '/Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/blog/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/test': RouteRecordInfo<'//Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/test', '/Users/incruisesja/Documents/GitHub/personal-website/client/src/pages/test', Record<never, never>, Record<never, never>>,
  }}
}
